version: '3'
services:
  nextjs:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run build && npm start"
